### ISSUE TITLE
Example using core.async

### ISSUE THREAD

**Issue by brandonpollack23** [cljfx/cljfx#124]
I'm currently learning clojure and was going to use cljfx for my next project.

I love it and I really appreciate the hard work that must have gone into making this.

You have one example where you have pure functions for events (18) and it is a good starting point, but I wonder if you could make an example that shows how one might use core.async with this library.  I can think of a couple of ways it might change things:

1. It is one way to decouple events from their effects (though you already do a pretty good job of this).  Right now your events come in as data already and you can even dispatch more events, but it's all on the UI thread and can have a little bit of coupling.  I _think_ you can use core.async to create a more reactive style app where you push any states/effects you want into channels and then whoever cares about those channels (eg go/thread calls) can react to them and update the state accordingly.
2. For HTTP it would be nice to see how one might put together an async channel and call go around the HTTP call instead of just using a callback that dispatches an event.

I'm curious if this is idiomatic or am I way off base?  I am not certain I'd need to even do any of this but it would be nice to know.

**Comment by vlaaad** [comment]
There is some asynchrony stuff with `wrap-async` event handler wrapper, but I eventually ended up removing all uses of it in real projects. The problem with async event handling is that it's incompatible with JavaFX event model that mutates events (e.g. to stop event propagation) during event dispatch. This makes any async handling less useful at best (it can't stop events) and confusing at least (attempts to stop event propagation do nothing since the event has already propagated). Unfortunately, you would be better off doing synchronous dispatch.
