### ISSUE TITLE
In a ListView how to detect a click?

### ISSUE THREAD

**Issue by ahungry** [cljfx/cljfx#15]
Sorry if I missed it, I searched the repo via github search and on the readme page - if I have a list of items (derived from the cells example, the one that lists out 16r1000 gradient colors), how can I detect which item in the list is clicked?

Ideally using the split view / state management functionality as shown in the other example script for handling events like `::set-done` without coupling functions to the view.

**Comment by vlaaad** [comment]
There is no way to set seleted item (which is a missing piece in cljfx, I'll add it) in list view, but at least you can observe selected item changes with `:on-selected-item-changed` prop:
```
(def list-view
  {:fx/type :list-view
   :cell-factory (fn [i]
                   (let [color (format "#%03x" i)]
                     {:style {:-fx-background-color color}
                      :text color}))
   :on-selected-item-changed prn
   :items (range 16r1000)})
```

**Comment by ahungry** [comment]
Thanks, on-selected-item-changed does the trick for now.

**Comment by vlaaad** [comment]
I added a way to specify not only selection change listener, but a selected item too. 

While `:on-selected-item-changed` will continue to work, it's no longer recommended approach, because there is nothing about selection in ListView itself, it's in a SelectionModel inside this list view, so this is a discrepancy between props in JavaFX and props in cljfx.

Recommended approach is to use a lifecycle that allows defining extra props: these can be whatever you want, and there is no expectation of props matching underlying JavaFX props. Selection-related props are included, so you don't have to write them yourself, see [example](https://github.com/cljfx/cljfx/blob/master/examples/e27_selection_models.clj).
