### ISSUE TITLE
Children: duplicate children added: when using pie-chart and dynamic rendering

### ISSUE THREAD

**Issue by challmand** [cljfx/cljfx#173]
When trying to update the pie-chart data dynamically with rendered I am getting this error:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Children: duplicate children added: parent = Chart$1@4c47f8b8[styleClass=chart-content]
	at javafx.scene.Parent$3.onProposedChange(Parent.java:561)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:205)
	at javafx.scene.chart.PieChart.dataItemAdded(PieChart.java:417)
	at javafx.scene.chart.PieChart.lambda$new$0(PieChart.java:168)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
.....
```

This is the code 

```
(defn chart-data [data]
  (for [d (set data)]
       {:fx/type :pie-chart-data
        :name d
        :pie-value (* 64 (count (filter #(= % d) data)))}))

(defn point-chart [data]
  {:fx/type :pie-chart
   :pref-height 600
   :title "Point Distribution"
   :data (chart-data data)})
```

I ran a trace of what is returned from `chart-data` and there are no duplicates. Is there some weird quirk when updating through the render where it doesnt clear the old data first?

Sorry if this is something completely obvious, I cannot see it.

**Comment by vlaaad** [comment]
Hi, this looks like a known JavaFX bug, there is a workaround described [here](https://github.com/cljfx/cljfx/issues/76#issuecomment-645563116). Does it help?

**Comment by challmand** [comment]
Awesome, yeah that worked. I initially looked at that post but the context didnt not immedielty stick out to be to be the same issue, guess it was. 

Thanks for the solution. A question on the :key, the example uses a count. In my case the count can be the same but be different data, would it be bad just to pass in the current data as the key so its unique? Or would making it a checksum of the data be better?

Appreciate all the help, just finished my first program with cljfx and it was a pleasure to use.

**Comment by vlaaad** [comment]
Hey, I also answered you [here](https://github.com/cljfx/cljfx/issues/76#issuecomment-1597658635) yesterday.

> In my case the count can be the same but be different data, would it be bad just to pass in the current data as the key so its unique

It's fine, you can pass the whole data instead of just the count. The resulting view should be the same. The only downside of that approach is a slightly increased garbage collection pressure since the pie chart node will be re-created on every datapoint change. The bug with the chart only appears when cljfx modifies a pie charts' data, and that only happens when there is a different *count* of pie chart data. If the count is the same but the values are different, only changes data are updated. Because of that, using `count` is enough with `ext-re-create-on-key-changed`, but of course, you can use the whole data structure instead of just its count if you want.
