### ISSUE TITLE
Overly conservative leaked context error?

### ISSUE THREAD

**Issue by frenchy64** [cljfx/cljfx#36]
While writing unit tests for an unrelated context bug, I made this minimal example of an interesting leaked context error:

```clojure
(require '[cljfx.context :as context])
(let [max-rounds 1
      *round (atom 0)
      f (fn f [context]
          (when (<= (swap! *round inc) max-rounds)
            (context/sub context f))
          (context/sub context :anything))
      context (context/create {} identity)
      _ (context/sub context f)]
  )

;Execution error (AssertionError) at cljfx.context/assert-not-leaked (context.clj:70).
;Assert failed: cljfx.context_test$eval2008$f__2009@508f2c52 is attempting to subscribe to bound context which already has value
;
;Possible reasons:
;- you return lazy seq which uses `cljfx.api/sub` while calculating elements
;- you leaked context from subscription function's scope without unbinding it first (call `cljfx.api/unbind-context` on it in that case)
;(not (has? cache sub-id))
```

There's no laziness or leaked contexts here, so is this a bug?

**Comment by vlaaad** [comment]
`assert-not-leaked` is a safety net to ensure all dependencies of a sub will be invalidated once sub's value changes when we create derived contexts. This example looks like a false positive to me, because context functions are assumed to be pure, and this function is not pure, and if it were, it would throw stack overflow exception.

**Comment by frenchy64** [comment]
Got it, thanks!
