### ISSUE TITLE
fxml support

### ISSUE THREAD

**Issue by slifin** [cljfx/cljfx#47]
Is there a way to use fxml files with this whilst still maintaining a repl based development flow?

**Comment by vlaaad** [comment]
Cljfx is an alternative to fxml that allows [iterating on a running application](https://github.com/cljfx/cljfx/blob/master/examples/e12_interactive_development.clj), what would you want fxml for? What is fxmls use case?

Answering your question, there are 2 approaches depending on what's your situation:
- if you prefer iterating on static layout using UI builder instead of in a live application using code, you can add a dependency on fxml (if on java 11) or just import it (present by default in java 8) and use it with `fx/ext-instance-factory` extension lifecycle;
- if you have existing fxml files that you want to convert to cljfx markup, you probably can just write a script that does conversion, it should be more or less straightforward.

**Comment by slifin** [comment]
Ok thank you for letting me know the options
The curiosity was born out of this talk: https://www.youtube.com/watch?v=PUv66718DII
