### ISSUE TITLE
Component re render firing when subscription isn't changing it's value.

### ISSUE THREAD

**Issue by jpmonettas** [cljfx/cljfx#57]
Please look at this repo https://github.com/jpmonettas/cljfx-test with a minimal example that reproduce the bug, it's readme contains instructions on how to reproduce.

**Comment by vlaaad** [comment]
Hi! 
Thanks for the repro, I've been able to reproduce the issue. Seems to be a bug in context implementation, it's cache has lots of deeply-nested `[:dirty [:dirty [:dirty ...]]]` entries. I'll think about it. 
I also noticed you don't have `core.cache` factory for the context, which will eventually lead to out of memory errors: see [example](https://github.com/cljfx/cljfx/blob/master/examples/e32_editable_table_cell_with_datascript.clj#L24).

This might be a very difficult bug to fix, context stuff turned out to be too damn hard to comprehend. I would suggest not using `fx/create-app`, perhaps you could use simple atom and renderer with passing data around.

**Comment by vlaaad** [comment]
Actually, I might have a solution, I'll need to test if thoroughly though...

**Comment by jpmonettas** [comment]
Hi! Thanks for looking at it @vlaaad. 
Yeah I tried to see if I could figure out what was wrong before reporting the bug but had a hard time wrapping my head around the code.

I was trying the subscriptions route because of performance issues, to avoid the entire diagram to be recalculated every time something simple like a node coordinate change.

Also I was seeing (checking with jvisualvm) lots of garbage being generated and collected while dragging the node around. Maybe it is not a good approach for things like this.

**Comment by vlaaad** [comment]
I think I might have fixed your issue. 

You need to use `core.cache` with contexts: I added `#(cache/lru-cache-factory % :threshold 256)` as a second parameter to `fx/create-context` and it stopped showing printing `"Rendering diagram"`. 

By the way, the fact that it's printed means that we call this function, it does not mean that any JavaFX objects will be re-created. The work cljfx does for checking if the current component description is the same as the previous one is still there, it just happens without calling your function.
