### ISSUE TITLE
How best to deal with conditionals node?

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#79]
What's the go-to way to deal with "nil" nodes?

For instance if I have a conditional buttons that only displays sometimes:

```clojure
 {:fx/type :h-box
  :pref-height height
  :min-height height
  :max-height height
  :alignment :center-left
  :children [{:fx/type :text
              :text "hi"}
             (if (fx/sub context
                         check-some-conditon)
               {:fx/type :button
                :text "A very special button"})
               ;;something?
             ]}
```

At times I've just put in a placeholder`:fx/type :pane` and at others I've done a `(filter some? ..)` on the vector. Maybe there is a better way about it?

**Comment by vlaaad** [comment]
I usually use `cond->` + `conj` (for single items) or `into` (for multiple items):
```clj
{:fx/type :h-box
 :children (-> [{:fx/type :text
                 :fx/key ::before
                 :text "A text that is always there, just putting it in a vec"}]
             (cond-> (fx/sub context check-some-condition)
               (conj {:fx/type :button
                      :fx/key ::conditional-button
                      :text "A conditionally added button"}))
             (conj {:fx/type :text
                    :fx/key ::after
                    :text "A text that is always there after conditional node"})
             (into [{:fx/type :text
                     :fx/key ::after
                     :text "Or I can use into"}
                    {:fx/type :text
                     :fx/key ::after
                     :text "for multiple children"}]))}
```
Another way is to use `concat` that concatenates multiple colls together, and rely on `nil` being treated as empty collection:
```clj
{:fx/type :h-box
 :children (concat 
             [{:fx/type :text
               :fx/key ::before
               :text "A text that is always there, just putting it in a vec"}]
             (when (fx/sub context check-some-condition)
               [{:fx/type :button
                 :fx/key ::conditional-button
                 :text "A conditionally added button"}])
             [{:fx/type :text
               :fx/key ::after
               :text "A single element after should still be wrapped in a vector"}])}
```

Note that I use `:fx/key` for cases where the child list of a node might change to minimize diffing: nodes in lists are diffed based on their `:fx/key` + index of such key's occurrence. In the first example, if we didn't specify keys, in the case of transition from having the button to not having it, cljfx would see that the second item was a button and now it's a text and will create a new one. Since there are keys, when the button disappears, cljfx will see that the text that should now be a second child already exists in a previous child list, and will just reorder children. 
It does not matter much on small nodes such as text, but performance impact might be huge for heavier nodes like tables, charts, etc.

**Comment by geokon-gh** [comment]
Ah okay. So I do need to filter out nils somehow one war or another. Thanks for the alternate solutions. I'll definitely be using those. And yes, the `:fx/key` thing is something I should keep in mind more. Is there some way you track if the node is reused or not? I'm not quite sure where I'd stick in a print statement :)

I know with the subscriptions you can just put in `println` (which reminds me that I need to adjust the cache size so I stop recomputing the cache all the time!). Do you have some equivalent for nodes?

**Comment by vlaaad** [comment]
It's more complicated with nodes for sure :)
There is `ext-on-instance-lifecycle` extension lifecycle that executes callbacks when an instance is created/replaced/deleted — see relevant [readme section](https://github.com/cljfx/cljfx#included-extension-lifecycles).
