### ISSUE TITLE
`wrap-async` not compatible with drag & drop

### ISSUE THREAD

**Issue by DerGuteMoritz** [cljfx/cljfx#93]
When wrapping the event handler function with `wrap-async`, calling `.startDragAndDrop` on an event's source object inside the event handler leads an exception like this:

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = clojure-agent-send-pool-5
```

`:fx/sync true` obviously doesn't help in this case because the method call still happens on the agent thread. Perhaps we're holding it wrong or missing something? :smile:

**Comment by vlaaad** [comment]
Hi @DerGuteMoritz,

The correctness of design decisions is sometimes can only be seen in retrospective. I'm glad I made `wrap-async` opt-in because with the time I started to dislike it. The initial intention was to make any kind of computations possible in event handlers without blocking the UI (which `wrap-async` allows). But even if it's not blocking the UI, it still blocks any other event processing: if pressing a button starts a long-running http request, you still will be able to click other buttons, but they will do nothing until the http request completes, so you still need to be thoughtful about long-running computations. So while the benefits of `wrap-async` are weak, the drawbacks are strong: increased complexity with `:fx/sync` necessary in some situations that are not obvious, e.g. text change handlers, any events you might want to stop propagation for...

I would suggest dropping the `wrap-async` altogether. Alternatively, you can try wrapping your `.startDragAndDrop` call in `(fx/on-fx-thread ...)` (and you probably should do it without `:fx/sync true` or without dereferencing the `on-fx-thread` call — I haven't tried, but I have a suspicion it might cause a deadlock if JavaFX thread blocks on agent thread that again blocks on JavaFX thread).

**Comment by vlaaad** [comment]
Feel free to reopen if this didn't help 👍

**Comment by DerGuteMoritz** [comment]
Hi @vlaaad,

thanks for your swift an detailed reply!

> The correctness of design decisions is sometimes can only be seen in retrospective. I'm glad I made `wrap-async` opt-in because with the time I started to dislike it. The initial intention was to make any kind of computations possible in event handlers without blocking the UI (which `wrap-async` allows). But even if it's not blocking the UI, it still blocks any other event processing: if pressing a button starts a long-running http request, you still will be able to click other buttons, but they will do nothing until the http request completes, so you still need to be thoughtful about long-running computations. So while the benefits of `wrap-async` are weak, the drawbacks are strong: increased complexity with `:fx/sync` necessary in some situations that are not obvious, e.g. text change handlers, any events you might want to stop propagation for...

That pretty much aligns with our assessment, as well. Seems like an easy solution to the problem at first, but as with all things "easy", it comes with a whole bunch of drawbacks :smile: Would you care about a PR to mark `wrap-async` as deprecated, while pointing to this issue here in the docstring? I would also update the instructions in the REAMDE accordingly.


> I would suggest dropping the `wrap-async` altogether. 

Yep, that's what we went with now. We're delegating blocking operations to another thread via `core.async` and everything works swimmingly so far. Unfortunately, we had to pretty much copy & paste `create-app` for that purpose. I created a PR to address this over here: https://github.com/cljfx/cljfx/pull/95

> Alternatively, you can try wrapping your `.startDragAndDrop` call in `(fx/on-fx-thread ...)` (and you probably should do it without `:fx/sync true` or without dereferencing the `on-fx-thread` call — I haven't tried, but I have a suspicion it might cause a deadlock if JavaFX thread blocks on agent thread that again blocks on JavaFX thread).

Oh right, I had tried that in fact, only forgot to mention it, sorry. That approach results in the following error:

```
java.lang.IllegalStateException: Cannot start drag and drop outside of DRAG_DETECTED event handler
```

**Comment by vlaaad** [comment]
Yes, PR for marking `wrap-async` as deprecated and updating the README is welcome! Instead of linking to the issue though I would prefer if the docstring for `wrap-async` had either a quick explanation why it's deprecated (e.g. creates more problems than solves) or, as it is with deprecated `sub`, a call to action (e.g. advice to use synchronous event handling).

It's fine to have your own variation of `create-app` — it's a starting point that you can reproduce using only cljfx's public APIs and build upon. I'll think about #95, currently, I'm torn about it since I'm not happy with having too many knobs in something that is mostly intended to be an example, while on the other hand it makes sense to deprecate `wrap-async` and allow turning it off there...

**Comment by DerGuteMoritz** [comment]
> Yes, PR for marking `wrap-async` as deprecated and updating the README is welcome! Instead of linking to the issue though I would prefer if the docstring for `wrap-async` had either a quick explanation why it's deprecated (e.g. creates more problems than solves) or, as it is with deprecated `sub`, a call to action (e.g. advice to use synchronous event handling).

Good point, better for the code to be self-contained. Here you go: https://github.com/cljfx/cljfx/pull/96

 
> It's fine to have your own variation of `create-app` — it's a starting point that you can reproduce using only cljfx's public APIs and build upon. I'll think about #95, currently, I'm torn about it since I'm not happy with having too many knobs in something that is mostly intended to be an example, while on the other hand it makes sense to deprecate `wrap-async` and allow turning it off there...

Yeah, agreed, the amount of knobs on that one is staggering :smile: I have to admit that I was a bit unsure about the recommended approach. But I guess we should continue that discussion on the relevant PR!
