### ISSUE TITLE
how do I set the focus of a component?

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#94]
In my case, I have a set of tabs and one of the tabs contains a 'search' text field that should be focused so the user can just start typing (rather than placing the cursor of the text field and click).

There is `requestFocus`, but where would I get a hold of a reference to the text field instance? I might be able to hook into a on-tab-changed type event and then search the components for the text field but is there a cljfx-way I'm overlooking?

**Comment by vlaaad** [comment]
I had a couple of variations of this extension lifecycle in different projects:
```clj
(defn focus-when-on-scene! [^Node node]
  (if (some? (.getScene node))
    (.requestFocus node)
    (.addListener (.sceneProperty node)
                  (reify ChangeListener
                    (changed [this _ _ new-scene]
                      (when (some? new-scene)
                        (.removeListener (.sceneProperty node) this)
                        (.requestFocus node)))))))

(defn ext-focused-by-default [{:keys [desc]}]
  {:fx/type fx/ext-on-instance-lifecycle
   :on-created focus-when-on-scene!
   :desc desc})
```
With this snippet, you can create component descriptions that automatically request focus when added to scene, e.g.:
```clj
{:fx/type ext-focused-by-default
 :desc {:fx/type :text-field}}
```
I'm not sure it's ready to be included in cljfx itself, because the exact focus behavior I needed was different from project to project, e.g. [Reveal](https://github.com/vlaaad/reveal/blob/ee62aee2e6a9e5b2f7f562381986585a635d64d5/src/vlaaad/reveal/ui.clj#L59-L86) uses a modified version of this code because the `:desc` can be any node graph and it is preferable to focus on focus-traversable node inside the desc, not on the root desc node itself.

**Comment by vlaaad** [comment]
If I understood your use-case correctly, you might want to adapt my snippet a bit by keeping the listener when the text field is added to the scene so switching tabs back and worth will still make it request focus. Anyway, the general gist of it is using `ext-on-instance-lifecycle` and requesting focus when it's added to scene (IIRC requesting the focus on a node that is not on a scene is a no-op). Feel free to reopen if that didn't help!

**Comment by torkus** [comment]
Thanks, @vlaaad . It didn't work for me unfortunately. The below works nicely:

```edn
  {:fx/type :tab-pane
   :tabs [{:fx/type :tab
           :text "tab1"
           :closable false
           :content {:fx/type ...}}
          {:fx/type :tab
           :text "tab2"
           :closable false
           :on-selection-changed (fn [ev]
                                   (when (-> ev .getTarget .isSelected)
                                     (let [text-field (-> ev .getTarget .getTabPane (.lookupAll "#id-of-my-text-field") first)]
                                       (Platform/runLater
                                        (fn []
                                          (-> text-field .requestFocus))))))
           :content {:fx/type ...}}]})
```

**Comment by vlaaad** [comment]
Glad you got it working! 👍
