### ISSUE TITLE
Explicitly state that subscription function identity is required for memoization

### ISSUE THREAD

**Issue by DerGuteMoritz** [cljfx/cljfx#97]
Hi again :smile:  

Just to be sure: The subscription mechanism requires that the function passed to `sub-ctx` and `sub-val` are `identical?` in order for the memoization to be effective, correct? If so, I suggest that to be mentioned explicitly in the relevant `README.md` section. Perhaps it could also be illustrated by means of a negative example, e.g. passing an anonymous function and labelling that as "don't to this".

**Comment by vlaaad** [comment]
Not quite: cljfx stores memoized results with the key being a data structure with fn and args, that data structure is checked with `=`, but equality for functions by default is reference equality (the same check that `identical?` performs), so you can say it is checked with `identical?` unless you make your functions have [equality semantics](https://vlaaad.github.io/transparent-functions). I agree this topic is a gotcha and might come as a surprise, so this can be mentioned — preferably in the gotchas section because this applies for function event handlers too. PR is welcome :)
